# This file configures the GitHub Actions workflow to deploy the Flutter Web app to Firebase Hosting on push to the main branch.
name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        working-directory: gmq_absensi

      - name: Build Flutter Web
        run: flutter build web --release
        working-directory: gmq_absensi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GMQ_ABSENSI }}'
          channelId: live
          projectId: gmq-absensi
          entryPoint: gmq_absensi
